# Generated by Django 4.2.5 on 2024-02-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_item_alter_account_id_alter_account_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='deafault.png', upload_to='img/%y'),
        ),
    ]
