# Generated by Django 4.2.5 on 2024-02-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/deafault.png', upload_to='img/%y'),
        ),
    ]
