# Generated by Django 5.0.2 on 2024-02-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
