# Generated by Django 5.0.2 on 2024-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.CharField(default='Black', max_length=100),
        ),
    ]
